### ISSUE TITLE
Possible mistake or missing information in the documentation for Android setup

### ISSUE THREAD

**Issue by NR005** [kuklinistvan/docker-anki-sync-server#13]
The documentation for the config on Android says:

> specify the same two urls you've specified on the desktop client.

For me this did not work. I had to leave out `/sync` in the url to get AnkiDroid to log in.
I testet this on AnkiDroid 2.9, 2.9.1 and 2.9.5. They all came up with a network error when trying to sign in with `http://192.168.0.10:27701/sync`. Anki on Windows (2.1.15) works perfectly fine with `http://192.168.0.10:27701/sync/`

**Comment by kuklinistvan** [comment]
Hello there,

Thank you for reporting! My mistake. I'm fixing the README soon!

**Comment by kuklinistvan** [comment]
I've tried the URLs on my computer and on my phone and I've put a small table in the doc with the working links.
