### ISSUE TITLE
Unable to login on Anki 2.1.23-1

### ISSUE THREAD

**Issue by ghost** [kuklinistvan/docker-anki-sync-server#15]
I was receiving the error at https://github.com/kuklinistvan/docker-anki-sync-server/issues/12 whilst attempting to login on Anki **2.1.15-1**, after manually installing the SyncRedirector addon (at `~/.local/share/Anki2/addons21`) as the addon on the website doesn't support that Anki version, and setting up the config.json with the values listed, e.g. `http://domain.com/sync` and `http://domain.com/msync`.

~~I decided to update to Anki **2.1.23-1** as it's available in the Arch Linux Community-Testing repository, which fixed the error I was receiving above.~~

**EDIT:** I've since reinstalled Anki **2.1.23-1** and found that updating wasn't what fixed https://github.com/kuklinistvan/docker-anki-sync-server/issues/12. The reason for this issue (for me) was because I had `http://domain.com/sync` and `http://domain.com/msync` and not  `https://domain.com/sync` and `https://domain.com/msync` - switching to https solved this issue for me, given that domain.com is https only.

However, I now receive a new error when attempting to login (no matter what the username and password input is):
```
Syncing failed:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aqt/sync.py", line 397, in run
    self._sync()
  File "/usr/lib/python3.8/site-packages/aqt/sync.py", line 420, in _sync
    self.hkey = self.server.hostKey(*self.auth)
  File "/usr/lib/python3.8/site-packages/anki/sync.py", line 571, in hostKey
    ret = self.req(
  File "/usr/lib/python3.8/site-packages/anki/sync.py", line 554, in req
    self.assertOk(r)
  File "/usr/lib/python3.8/site-packages/anki/sync.py", line 487, in assertOk
    raise Exception("Unknown response code: %s" % resp.status_code)
Exception: Unknown response code: 404
```

I've tried every combination of `http://domain.com/sync`, `http://domain.com/`, `http://domain.com`, etc on config.json - assuming it was to do with reaching a 404 on domain.com, however that made no difference.

For reference, when visiting these URLs in a browser:
`http://domain.com/` displays `Anki Sync Server`.
`http://domain.com/sync` and `http://domain.com/msync` both return 404.

This is a fresh install using docker-compose and nginx (with a reverse proxy from 127.0.0.1:27701 to domain.com), hosted on a server.

Any help would be appreciated, thanks for your hard work. :)

**Comment by ghost** [comment]
Nevermind, my nginx config for domain.com had 
```
location / {
    try_files $uri $uri/ = 404;
    ...
}
```

Removing that line resulted in both `http://domain.com/sync` and `http://domain.com/msync` to begin returning `Anki Sync Server` which fixed logging in - I had a strong impression it was to do with those returning 404.

Due to how new Anki **2.1.23-1** is, you receive the message:
```
Your client is using unsupported sync protocol (10, supported version: 9)
```
Which is mentioned in https://github.com/tsudoko/anki-sync-server/issues/63, applying that fix allows you to login, whilst we wait for https://github.com/tsudoko/anki-sync-server/pull/60 to merge.

I'll close this and leave it for anyone else who comes across these issues.

Thanks again.

**Comment by kuklinistvan** [comment]
Hello,

thank you for troubleshooting the issue! The detailed information you provided may help someone else in the future ;)

As I'm aware of that tsudoko's server implementation officially [does not support your version](https://github.com/tsudoko/anki-sync-server#installing), I'm targeting an older one.

Although neither 2.1.19 is supported by that implementation, with their help I was able to create a fork (by applying an extra commit) that I could test successfully, therefore desktop version 2.1.19 can be used with this image.

If you wish to use this dockerized solution, then I suggest you to download [those clients that I have tested with](https://github.com/kuklinistvan/docker-anki-sync-server#tested-client-downloads). Recently I have created mirrors for them too in order to always have a working configuration, regardless how Anki changes in the future.

Regards,
István

**Comment by ghost** [comment]
Hi István,

Here's what I found (based on my limited testing):

**2.1.23** reports `AnkiWeb ID or password is incorrect; please try again` but synchronises anyway, however closing Anki after the first sync causes it to try synchronising forever. Attempting to reopen Anki after killing the process will also cause it to synchronise forever, ultimately leading to it being unusable as you cannot reopen Anki.

**2.1.22** reports `AnkiWeb ID or password is incorrect; please try again`  but synchronises anyway, no other issues.

Versions **2.1.19** to  **2.1.21** all work fine.

I got versions 2.1.20 and upwards from https://github.com/ankitects/anki and ran `./bin/anki` as mentioned in the Makefile for the Linux releases, version 2.1.19 is from this repository.

Hope this helps somewhat - thanks for your advice. :)

**Comment by kuklinistvan** [comment]
It will indeed come in hand and could help me when I'm updating the repository and the image.

Unfortunately I'm busy with my assignments in the following days or weeks to test a new version, but I will check back later.

Thanks again!

**Comment by kuklinistvan** [comment]
@tsudoko, you may find [that](#issuecomment-612635568) interesting too!
