### ISSUE TITLE
2.1.19 client download for OS X is not present on AnkiWeb

### ISSUE THREAD

**Issue by ndroftheline** [kuklinistvan/docker-anki-sync-server#17]
Thanks very much for this great project. 

I've got your container running, and have Anki Desktop running on my Windows 10 desktop and Anki Desktop running on my MacOS Mojave laptop, with the plugin installed and configured with my anki sync server's IP. I'm able to curl the page from the Mac: 

```
$ curl http://192.168.11.60:27701/msync
Anki Sync Server
$ curl http://192.168.11.60:27701/sync
Anki Sync Server
```

I've got a user set up on the anki sync server and profiles of the same name configured on each machine, but nothing appears to be syncing; cards made on one machine don't show up on the other machine, and  my data/collections/<username> directory is empty: 

root@foinix:/gnosis/AppData/ankisyncd/data/collections/ndroftheline# ls
root@foinix:/gnosis/AppData/ankisyncd/data/collections/ndroftheline#

so I'm afraid I've missed something, anything you can recommend I try? 

Thanks again!

**Comment by kuklinistvan** [comment]
Hello,

Thank you for the detailed report!

Can you describe the exact steps you've taken to configure the clients? If I understood correctly, 

1. You've set up the server
2. You've set up the desktop clients with `SyncRedirector`
3. **What was the third step and what happened instead of the expectation? :)**

After configuring and you should restart the desktop client (you probably did) and then ask for synchronization (last button in the top of the main window). Then it should prompt you for the credentials, then sync. 

Any screenshot, log, or observation may help.

P.S.: also note that as of yet, I'm supporting only AnkiDesktop version 2.1.19

**Comment by ndroftheline** [comment]
Hey, thanks for the prompt and clear response.

I didn't know pressing the Sync button was a required step; it doesn't appear to indicate so here https://github.com/kuklinistvan/docker-anki-sync-server#ankidesktop . I must have missed somethign?

When I press that button, it pops up an input box titled "Anki" reading 
"Account Required 
A free account is required to keep your collection syncronized. Please sign up for an account, then enter your details below. 
AnkiWeb ID: [string input field] 
Password: [string input field]" 

I had actually pressed that button somewhat on accident before, and discarded it as relevant because it seems to point only at the cloud service AnkiWeb. 

I am using version 2.1.22, woops. Perhaps that is my main problem, because I can see clearly that your links are for 2.1.19, and even the SyncRedirector plugin says (requires Anki <= 2.1.19). Let me try that...

I tried using the link in your documentation https://github.com/kuklinistvan/docker-anki-sync-server#tested-client-downloads but that only downloads the Linux version (and it's not marked as such); so I sought out my own download of AnkiDesktop on Google. I found this: https://apps.ankiweb.net/ which currently appears to only list three versions: 2.1.26 (referred to as "just released"), 2.1.22 (referred to as "recent stable"), and 2.1.15 (referred to as "older"); seeking other versions, I tried to find a link to a more comprehensive releases page but after a couple minutes clicking on random links, just tried to google "ankidesktop github" and chose this: https://github.com/ankitects/anki ; no real idea if this is the right repo...comparing it to the download links on the other page, it looks right though, so feeling OK. Clicking on that page's releases link, and carefully reading through the entires, I find only the source code for 2.1.19, no "release" for 2.1.19. I go back to your download page to see where your AnkiDesktop download points...which points to the AnkiDownloads site I was on orignally. Removing the filename on the end of the URL i'm just redirected to the main apps.ankiweb.com site, which no option of downloading 2.1.19...opening Development tab I finally find a link that reads "other old downloads" and am brought to this: https://apps.ankiweb.net/downloads/archive/ ...but still no 2.1.19 versions. 

I guess I'll try 2.1.15, since that's less than 2.1.19 so in theory it should be compatible but not confirmed working accoridng to your github docs... found the executable here: https://github.com/ankitects/anki/releases?after=2.1.18

Removed 2.1.22, installed 2.1.15, confirmed running 2.1.15 from Help > About; confirmed syncredirector plugin installed and configured to point at my ankisyncd instance (and re-confirmed i can still curl it); clicked Sync button, but received the same login popup for an AnkiWeb ID. 

So I'm starting to build up to the potential understanding that I'm supposed to input the credentials I set up on my own sync server in here instead of the AnkiWeb ID and password it asks for? I'll try that...OK, i'm getting a merge problem reported, i'll overwrite what the "server" has...."Your collection was successfully uploaded to AnkiWeb"...appears working!

Open my macbook, remove 2.1.23 (the current recommended stable release) and install 2.1.15, check syncredirector plugin config, click sync, type in my own credentials, overwrite local database with server database...appears to be working there too. 

I think this is now working, albeit with very little testing so far. 

I'm not sure that the version made a difference, or it was just that I was completely missing the "press the sync button and sign in with your custom ankisyncd credentials, NOT ankiweb credentials" step. Anyway, 2.1.15 is confirmed working on both Windows 10 Pro and MacOS Mojave. 

Neato. I'll see about making a PR on your documentation to make it clearer for noobs like me. 

Thanks again! Do you have a tip jar somewhere?

**Comment by kuklinistvan** [comment]
Hello,

I've updated the README, the last step regarding to the Sync button is now included.

Although I'm happy hearing that version 2.1.15 works, I'm still supporting only version 2.1.19 and prefer to keep it that way. (as my intention is not to have a broad range of supported versions but to have one set of versions with painless configuration)

Feel free to fork the repository though!

**Comment by AntonOfTheWoods** [comment]
> Although I'm happy hearing that version 2.1.15 works, I'm still supporting only version 2.1.19 and prefer to keep it that way. 

I had a look in Anki's previous versions repo and the current releases and I also couldn't find binaries for 2.1.19. That means users will have to build their own, which is a bit of a pain... Does GitHub allow mirroring someone else's binaries?

**Comment by kuklinistvan** [comment]
Although the hyperlink to this version of the binary does not appear for me to be directly present on the website of AnkiWeb, however, at least the client for GNU/Linux is still hosted - (the link is not broken in the README, [see it here](https://github.com/kuklinistvan/docker-anki-sync-server#tested-client-downloads)).

To my best knowledge you can mirror Anki binaries as long as you comply with [the open source licenses](https://github.com/ankitects/anki/blob/master/LICENSE). I'm not aware of the limitations of GitHub, but if problems occur, you are always free to host the binaries anywhere else and should be able to link it in your README.

If you have been able to build the client for Mac OS X, I'm happy to put a link to you efforts in the README of this repository.

**Comment by AntonOfTheWoods** [comment]
> Although the hyperlink to this version of the binary does not appear for me to be directly present on the website of AnkiWeb, however, at least the client for GNU/Linux is still hosted - (the link is not broken in the README, [see it here](https://github.com/kuklinistvan/docker-anki-sync-server#tested-client-downloads)).

Actually you are quite right, the link is not broken, and the links for Windows and Mac are also still available:
`https://apps.ankiweb.net/downloads/current/anki-2.1.19-mac.dmg` and `https://apps.ankiweb.net/downloads/current/anki-2.1.19-windows.exe`

`2.1.17` onwards appear to be available by changing the version numbers in `/downloads/current/` and `2.1.15` and `2.1.16` in `/downloads/archive/`. It's obviously just a user-friendliness issue we're talking about but it might be nice for some users to have these at the ready in your wonderful `Readme` :-).

**Comment by kuklinistvan** [comment]
I've updated the [README](https://github.com/kuklinistvan/docker-anki-sync-server#tested-client-downloads) and mirrored those installers too in case it gets taken elsewhere.

I'm glad you liked it :)

**Comment by AntonOfTheWoods** [comment]
You are a scholar and a gentleman! :-)

**Comment by kuklinistvan** [comment]
I'm closing this issue as the problem looks solved for me - feel free to reopen if you have further suggestions or questions :)
