### ISSUE TITLE
anki 更新之后插件无法使用；The plugin is not available after the anki update

### ISSUE THREAD

**Issue by kunpeng9** [kuklinistvan/docker-anki-sync-server#19]
* **AnkiDesktop version number:**
* **AnkiDroid version number:**
版本 2.1.26 (70784154)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Version 2.1.26 (70784154).
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
## Summary

Reproduction (what did you do - the more details you give, the better):
![image](https://user-images.githubusercontent.com/44609485/82444008-189ee700-9ad5-11ea-862f-e8ba885cd90a.png)
显示插件无法使用，需要anki的版本小于某个版本才行。什么时候可以更新插件？增加对新版本的支持？
The display plug-in is not available and requires a smaller version of anki. When can the plug-in be updated? Add support for the new version?
What was expected to happen:

What happened instead (the more details you give, the better):

**Comment by kuklinistvan** [comment]
Hello,

This plugin was created to make setting up your client to sync against the server encapsulated in this Docker image easier.

This image is backed by [the fork of ankisyncd maintained by tsudoko and their contributors](https://github.com/tsudoko/anki-sync-server), and I'm supporting one of the recent versions they support. I'm going to update this repository, and along with that `SyncRedirector` somewhat after a new server version is released in the former mentioned repository.

You may learn more about the reason I'm supporting only AnkiDesktokp version 2.1.19 at the moment here: https://github.com/kuklinistvan/docker-anki-sync-server/issues/16#issuecomment-626304807

You are free, however, to fork the repository and reupload the plugin with a broader range of supported versions.

Feel free to reopen this issue if you have further questions or suggestions.
