### ISSUE TITLE
Merge with tsudoku/anki-sync-server?

### ISSUE THREAD

**Issue by AntonOfTheWoods** [kuklinistvan/docker-anki-sync-server#2]
Is there a particular reason for not wanting to add Docker support directly to tsudoku/anki-sync-server and adding the Docker setup docs to a file there (or the wiki)? I have just submitted a PR reorganising the code for better extensibility (https://github.com/tsudoko/anki-sync-server/pull/13), and support for configuring all values via environment variables (https://github.com/tsudoko/anki-sync-server/pull/14). It would be great to centralise our efforts to Make Ankisyncd Great Again :-).

**Comment by kuklinistvan** [comment]
Hi! Thank you for opening the issue! I simply haven't thought about it but I like the idea! Stay tuned :)

**Comment by kuklinistvan** [comment]
Tsudoko has recently placed a link in their README :)
