### ISSUE TITLE
SyncRedirector do not support anki version after 2.1.19

### ISSUE THREAD

**Issue by bfcs** [kuklinistvan/docker-anki-sync-server#20]
* **AnkiDesktop version number: 2.1.26**
* **AnkiDroid version number:2.11.0**

## Summary

Reproduction (what did you do - the more details you give, the better): Using docker-anki-sync-server in anki latest version 

What was expected to happen: SyncRedirector do not support the version 

What happened instead (the more details you give, the better):

**Comment by kuklinistvan** [comment]
Hello there,

Please find the reason I'm supporting only version 2.1.19 at this moment here: https://github.com/kuklinistvan/docker-anki-sync-server/issues/16#issuecomment-626304807

Feel free to open this issue again if you have further suggestions or questions!
