### ISSUE TITLE
Create a team of maintainers

### ISSUE THREAD

**Issue by VikashKothary** [kuklinistvan/docker-anki-sync-server#21]
Hey , Thank you for all your hand work.

I created https://github.com/ankicommunity to allow a team of maintainers to work together to help maintain the original anki-sync-server and other projects like it.

I recently found this project and can see all the hard work you've put into dockerizing the @tsudoko's project. I want to offer my help and would love if you'd consider moving this project to our organisation. We've currently forked your repo but it would be great to have your say in upcoming improvements.

Also see: https://github.com/tsudoko/anki-sync-server/issues/70.

**Comment by kuklinistvan** [comment]
Hello,

Thank you for contacting! Let's continue this discussion at https://github.com/tsudoko/anki-sync-server/issues/70
