### ISSUE TITLE
please update image on the docker hub.

### ISSUE THREAD

**Issue by lurdan** [kuklinistvan/docker-anki-sync-server#4]
Because Anki 2.1.9 requires recent updates of tsudoko/anki-sync-server.

I've run your build.sh locally and it runs fine. Thanks in advance.

**Comment by kuklinistvan** [comment]
Hello there,

thank you for notifying me! I am going to rebuild the image soon, test it, and push it to DockerHub. Stay tuned!

**Comment by kuklinistvan** [comment]
For now, I have created the tag `tsudoku-2.1.9` on DockerHub. If it does not break in the next few day, I will update the latest tag and README.md as well!

**Comment by kuklinistvan** [comment]
If someone has found this bug, the symptoms include an error message on trying to synchronize Anki Desktop version 2.1.9.

> Syncing failed:
> AnkiWeb encountered an error. Please try again in a few minutes, and if the problem persists, please file a bug report.

**Comment by kuklinistvan** [comment]
Done :)
