### ISSUE TITLE
Ankidroid media sync issue

### ISSUE THREAD

**Issue by adamwolf** [kuklinistvan/docker-anki-sync-server#5]
Hi folks!

I tried this today.  I created a new user, logged in successfully in Ankidroid, and synced.  It says it synced the collection fine, but failed syncing the media data.

Collection synchronized

Error syncing media data

org.json.JSONException: Value Anki of type java.lang.String cannot be converted to JSONObject

I tried it a few times, and it's consistent.

I am on AnkiDroid 2.8.4.

**Comment by tsdko** [comment]
If your media sync URL contains trailing `/`s, try removing them. If the problem still persists, it would be nice to know if there are any requests logged by the server.

**Comment by adamwolf** [comment]
Works like a charm!  For reference, if you are doing an UNENCRYPTED sync, it will look something like:

http://IPADDRESS:27701/
and 
http://IPADDRESS:27701/msync

in Ankidroid.

**Comment by ghost** [comment]
Hey!

I am getting the same error message, but I already double-checked that there are no trailing slashes.

There is a logged request and it looks a lot like the requests made by my desktop, but it ends in 200 16 and not 200 52, if that is useful at all.
